#YAML
DATA:
  PATH_PRICES: '.\data_prices\'
  PATH_SALES: '.\data_sales\'
  PATH_CUSTOMERS_INFO: '.\customers_info\'
  PATH_SALES_GROUP: '.\data_sales_group\'
  FILE_NAME_SALES_GROUP: 'sales_group.csv'